# Country flags and metadata
COUNTRY_FLAGS = {
    "USA": "🇺🇸",
    "Mexico": "🇲🇽",
    "Canada": "🇨🇦",
    "Argentina": "🇦🇷",
    "Brazil": "🇧🇷",
    "Uruguay": "🇺🇾",
    "Chile": "🇨🇱",
    "Colombia": "🇨🇴",
    "Ecuador": "🇪🇨",
    "Paraguay": "🇵🇾",
    "Peru": "🇵🇪",
    "Venezuela": "🇻🇪",
    "Bolivia": "🇧🇴",
    "France": "🇫🇷",
    "Germany": "🇩🇪",
    "Spain": "🇪🇸",
    "England": "🇬🇧",
    "Italy": "🇮🇹",
    "Netherlands": "🇳🇱",
    "Belgium": "🇧🇪",
    "Portugal": "🇵🇹",
    "Poland": "🇵🇱",
    "Ukraine": "🇺🇦",
    "Serbia": "🇷🇸",
    "Croatia": "🇭🇷",
    "Austria": "🇦🇹",
    "Czech Republic": "🇨🇿",
    "Switzerland": "🇨🇭",
    "Denmark": "🇩🇰",
    "Sweden": "🇸🇪",
    "Norway": "🇳🇴",
    "Iceland": "🇮🇸",
    "Greece": "🇬🇷",
    "Romania": "🇷🇴",
    "Hungary": "🇭🇺",
    "Slovakia": "🇸🇰",
    "Slovenia": "🇸🇮",
    "Bosnia and Herzegovina": "🇧🇦",
    "Montenegro": "🇲🇪",
    "Albania": "🇦🇱",
    "North Macedonia": "🇲🇰",
    "Bulgaria": "🇧🇬",
    "Japan": "🇯🇵",
    "South Korea": "🇰🇷",
    "China": "🇨🇳",
    "Australia": "🇦🇺",
    "Saudi Arabia": "🇸🇦",
    "Iran": "🇮🇷",
    "Iraq": "🇮🇶",
    "Israel": "🇮🇱",
    "Uzbekistan": "🇺🇿",
    "Kyrgyzstan": "🇰🇬",
    "India": "🇮🇳",
    "Thailand": "🇹🇭",
    "Vietnam": "🇻🇳",
    "Philippines": "🇵🇭",
    "Indonesia": "🇮🇩",
    "Malaysia": "🇲🇾",
    "Singapore": "🇸🇬",
    "Egypt": "🇪🇬",
    "Morocco": "🇲🇦",
    "Nigeria": "🇳🇬",
    "Senegal": "🇸🇳",
    "Tunisia": "🇹🇳",
    "Algeria": "🇩🇿",
    "Ghana": "🇬🇭",
    "South Africa": "🇿🇦",
    "Cameroon": "🇨🇲",
    "Mali": "🇲🇱",
    "Costa Rica": "🇨🇷",
    "Panama": "🇵🇦",
    "Jamaica": "🇯🇲",
    "Honduras": "🇭🇳",
    "Trinidad and Tobago": "🇹🇹",
    "New Zealand": "🇳🇿",
    "Samoa": "🇼🇸",
    "Fiji": "🇫🇯",
}

SPORT_COLORS = {
    "primary": "#1f77e3",      # Sporty blue
    "secondary": "#ff6b35",    # Energy orange
    "accent": "#ffd60a",       # Gold
    "success": "#06a77d",      # Victory green
    "warning": "#f77f00",      # Alert orange
    "danger": "#d62828",       # Red
    "dark": "#1a1a1a",         # Dark background
    "light": "#f8f9fa",        # Light background
}

POSITION_GROUPS = {
    "Goalkeeper": "🥅",
    "Defender": "🛡️",
    "Midfielder": "⚙️",
    "Forward": "⚽",
    "F": "⚽",
    "M": "⚙️",
    "D": "🛡️",
    "G": "🥅",
}

# Continent mapping for countries
CONTINENT_MAP = {
    "North America": ["USA", "Mexico", "Canada"],
    "South America": ["Argentina", "Brazil", "Uruguay", "Chile", "Colombia", "Ecuador", "Paraguay", "Peru", "Venezuela", "Bolivia"],
    "Europe": ["France", "Germany", "Spain", "England", "Italy", "Netherlands", "Belgium", "Portugal", "Poland", "Ukraine", "Serbia",
               "Croatia", "Austria", "Czech Republic", "Switzerland", "Denmark", "Sweden", "Norway", "Iceland", "Greece", "Romania",
               "Hungary", "Slovakia", "Slovenia", "Bosnia and Herzegovina", "Montenegro", "Albania", "North Macedonia", "Bulgaria"],
    "Asia": ["Japan", "South Korea", "China", "Saudi Arabia", "Iran", "Iraq", "Israel", "Uzbekistan", "Kyrgyzstan", "India",
             "Thailand", "Vietnam", "Philippines", "Indonesia", "Malaysia", "Singapore"],
    "Africa": ["Egypt", "Morocco", "Nigeria", "Senegal", "Tunisia", "Algeria", "Ghana", "South Africa", "Cameroon", "Mali"],
    "Americas (Central/Caribbean)": ["Costa Rica", "Panama", "Jamaica", "Honduras", "Trinidad and Tobago"],
    "Oceania": ["Australia", "New Zealand", "Samoa", "Fiji"],
}
